package com.payroll.interfaces;
public interface EmployeeInterface extends Comparable<EmployeeInterface>
{

public void setName(String name);
public void setAddress(String address);
public void setContact(long contact);
public void setGender(String gender);
public void setAge(int age);
public void setEmail(String email);
public void setMeritalStatus(String meritalStatus);
public void setDateOfBirth(String dob);
public void setState(String state);
public void setCity(String city);
public void setBloodGroup(String bloodGroup);
public void setID(long ID);
public void setPassword(String password);
public void setDesignation(String designation);
public void setDearnessAllowance(int dearness);
public void setCityCompensatoryAllowance(int cityCompensatory);
public void setOtherAllowance(int other);
public void setDailyAllowance(int daily);
public void setMedicalAllowance(int medical);
public void setHomeRentAllowance(int homeRent);
public void setVehicleAllowance(int vehicle);
public void setOverTimeAllowance(int overTime);
public void setLifeInsurance(int lifeInsurance);
public void setGeneralProvidentFund(int generalProvidentFund);
public void setIncomeTax(int incomeTax);
public void setOtherTax(int otherTax);
public void setDeduction(int lifeInsurance,int generalProvidentFind, int incomeTax,int otherTax );
public void setNetSalary(double salary);
public void setLastLoginState(String time);
public void setAttendence(int count);
public void setLoginState(int bit);
public String getName();
public String getAddress();
public long getContact();
public String getGender();
public int getAge();
public String getMeritalStatus();
public String getState();
public String getCity();
public String getPassword();
public long getID();
public double getNetSalary();
public int getAllowance();
public int getDearnessAllowance();
public int getCityCompensatoryAllowance();
public int getOtherAllowance();
public int getDailyAllowance();
public int getMedicalAllowance();
public int getHomeRentAllowance();
public int getVehicleAllowance();
public int getOverTimeAllowance();
public int getLifeInsurance();
public int getGeneralProvidentFund();
public int getIncomeTax();
public int getOtherTax();
public int getDeduction();
public String getBloodGroup();
public String getEmail();
public String getDateOfBirth();
public String getDesignation();
public String getLastLoginState();
public int getAttendence();
public int getLoginState();
public boolean equals(Object object);
public String toString();
}